[project]
name = "pvserv"
version = "0.1.0"
description = "A Plotly plot viewing server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask",
    "flask_socketio",
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "plotly>=6.1.1",
    "scikit-learn>=1.6.1",
]
