[project]
name = "pvserv"
version = "0.1.0"
description = "A Plotly plot viewing server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask",
    "flask_socketio",
    "uv"
]
