#!/usr/bin/env bash

REPO_ROOT=$(git rev-parse --show-toplevel)

cd $REPO_ROOT

echo
echo 'pulling changes'
git pull

echo
echo 'removing old container & image'
docker stop pvserv
docker rm pvserv
docker rmi pvserv

echo
echo 'rebuilding image'
nix build .#docker
echo 'image build complete'

echo
echo 'loading image'
docker load < result

echo
echo 'creating container'
docker run -dit \
  -p 8080:8080 \
  -v  $REPO_ROOT/.data/db.sqlite3 \
  --name pvserv pvserv:latest
